#include "keydrop/schema/schema_config.hpp"

#include <cctype>
#include <fstream>
#include <iomanip>
#include <sstream>

namespace keydrop {
namespace {
std::string trim(std::string s) { const auto b=s.find_first_not_of(" \t\r"); const auto e=s.find_last_not_of(" \t\r"); return b==std::string::npos ? "" : s.substr(b,e-b+1); }
std::string unquote(std::string s) { s=trim(s); if(s.size()>=2 && ((s[0]=='"'&&s.back()=='"')||(s[0]=='\''&&s.back()=='\''))) return s.substr(1,s.size()-2); return s; }
bool number(const std::string& s, u64& v) { try { size_t n=0; v=std::stoull(s,&n,0); return n==s.size(); } catch(...) { return false; } }
u64 fnv(const std::string& s, u64 h=1469598103934665603ULL) { for(unsigned char c:s) { h^=c; h*=1099511628211ULL; } return h; }
bool split_kv(const std::string& line,std::string& k,std::string& v) { const auto p=line.find(':'); if(p==std::string::npos) return false; k=trim(line.substr(0,p)); v=unquote(line.substr(p+1)); return !k.empty(); }
FieldType alias_type(const std::string& type, bool& ok) { FieldType out; ok=try_parse_field_type(type,out); if(!ok) { static const std::pair<const char*,FieldType> aliases[]={{"uint8",FieldType::u8},{"uint16",FieldType::u16},{"uint32",FieldType::u32},{"int8",FieldType::i8},{"int16",FieldType::i16},{"int32",FieldType::i32},{"float",FieldType::f32},{"double",FieldType::f64}}; for(const auto& a:aliases) if(type==a.first) {ok=true;return a.second;} } return out; }
std::string json_escape(const std::string& s) { std::string o; for(char c:s) { if(c=='"'||c=='\\') o+='\\'; o+=c; } return o; }
}

u32 SchemaConfig::stable_field_id(const std::string& schema, const std::string& field) { return static_cast<u32>(fnv(schema + ":" + field)); }
u64 SchemaConfig::fingerprint(const ConfiguredSchema& s) { u64 h=fnv(s.schema.schema_name); h=fnv("|"+std::to_string(s.schema.message_id)+"|"+std::to_string(s.version),h); for(usize i=0;i<s.schema.fields.size();++i) h=fnv("|"+s.schema.fields[i].name+":"+field_type_to_string(s.schema.fields[i].type)+":"+std::to_string(s.field_ids[i]),h); return h; }

SchemaConfigResult SchemaConfig::load_yaml_file(const std::string& path,std::vector<ConfiguredSchema>& out) { std::ifstream f(path); if(!f) return {SchemaConfigCode::io_error,"Cannot open configuration: "+path}; std::ostringstream s;s<<f.rdbuf();return load_yaml(s.str(),out); }
SchemaConfigResult SchemaConfig::load_yaml(const std::string& yaml,std::vector<ConfiguredSchema>& out) {
 out.clear(); ConfiguredSchema current; bool in_schemas=false,in_fields=false,have=false; FieldDef pending{}; u32 pending_id=0; bool pending_have=false,pending_has_type=false;
 auto finish_field=[&]()->SchemaConfigResult { if(!pending_have) return {}; if(pending.name.empty()) return {SchemaConfigCode::missing_value,"Field is missing key."}; if(!pending_has_type) return {SchemaConfigCode::missing_value,"Field '"+pending.name+"' is missing type."}; if(pending.index!=current.schema.fields.size()) pending.index=current.schema.fields.size(); current.schema.fields.push_back(pending); current.field_ids.push_back(pending_id?pending_id:stable_field_id(current.schema.schema_name,pending.name)); pending={};pending_id=0;pending_have=false;pending_has_type=false;return {}; };
 auto finish_schema=[&]()->SchemaConfigResult { auto r=finish_field();if(!r.ok())return r; if(!have)return {}; if(current.schema.schema_name.empty()||current.schema.message_id==0)return {SchemaConfigCode::missing_value,"Schema requires name and id."}; auto valid=SchemaValidator::validate_schema(current.schema);if(!valid.ok())return {SchemaConfigCode::schema_invalid,valid.message}; current.fingerprint=fingerprint(current);out.push_back(current);current={};have=false;in_fields=false;return {}; };
 std::istringstream lines(yaml);std::string raw;usize line_no=0;
 while(std::getline(lines,raw)){++line_no; const auto hash=raw.find('#');if(hash!=std::string::npos)raw.resize(hash); if(trim(raw).empty())continue; const usize ind=raw.find_first_not_of(' '); if(ind==std::string::npos)return {SchemaConfigCode::syntax_error,"Tabs are not supported at line "+std::to_string(line_no)}; std::string line=trim(raw),k,v;
  if(line=="keydrop: 1")continue; if(line=="schemas:"){in_schemas=true;continue;} if(!in_schemas)return {SchemaConfigCode::syntax_error,"Expected 'schemas:' before line "+std::to_string(line_no)};
  if(ind==2 && line.back()==':'){auto r=finish_schema();if(!r.ok())return r;current.schema.schema_name=line.substr(0,line.size()-1);have=true;continue;}
  if(!have)return {SchemaConfigCode::syntax_error,"Expected schema name at line "+std::to_string(line_no)};
  if(ind==4 && line=="fields:"){in_fields=true;continue;}
  if(ind==4 && split_kv(line,k,v)){ if(k=="id"){u64 n;if(!number(v,n)||n==0||n>65535)return {SchemaConfigCode::invalid_value,"Schema id must be 1..65535."};current.schema.message_id=static_cast<u16>(n);} else if(k=="version"){u64 n;if(!number(v,n)||n==0||n>65535)return {SchemaConfigCode::invalid_value,"Schema version must be 1..65535."};current.version=static_cast<u16>(n);} else if(k=="profile")current.profile=v; else return {SchemaConfigCode::unsupported_feature,"Unsupported schema option '"+k+"'."};continue; }
  if(in_fields && ind>=6){ if(line.rfind("- ",0)==0){auto r=finish_field();if(!r.ok())return r;pending_have=true;line=trim(line.substr(2));} if(!pending_have||!split_kv(line,k,v))return {SchemaConfigCode::syntax_error,"Invalid field at line "+std::to_string(line_no)}; if(k=="key")pending.name=v; else if(k=="type"){bool ok=false;pending.type=alias_type(v,ok);if(!ok)return {SchemaConfigCode::invalid_value,"Unknown type '"+v+"' for field '"+pending.name+"'."};pending_has_type=true;} else if(k=="id"){u64 n;if(!number(v,n)||n==0||n>0xffffffffULL)return {SchemaConfigCode::invalid_value,"Field id must be 1..4294967295."};pending_id=static_cast<u32>(n);} else if(k=="max_length"){u64 n;if(!number(v,n)||n>65535)return {SchemaConfigCode::invalid_value,"max_length must be 0..65535."};pending.constraints={true,static_cast<usize>(n)};} else return {SchemaConfigCode::unsupported_feature,"Unsupported field option '"+k+"'."};continue; }
  return {SchemaConfigCode::syntax_error,"Unexpected YAML at line "+std::to_string(line_no)};
 }
 auto r=finish_schema(); if(!r.ok())return r; return out.empty()?SchemaConfigResult{SchemaConfigCode::missing_value,"Configuration contains no schemas."}:SchemaConfigResult{};
}
SchemaConfigResult SchemaConfig::check_compatible(const ConfiguredSchema& a,const ConfiguredSchema& b){if(a.schema.schema_name!=b.schema.schema_name)return {SchemaConfigCode::compatibility_mismatch,"Schema names differ."};if(a.schema.message_id!=b.schema.message_id)return {SchemaConfigCode::compatibility_mismatch,"Schema IDs differ."};if(a.version!=b.version)return {SchemaConfigCode::compatibility_mismatch,"Schema version mismatch: local "+std::to_string(a.version)+", peer "+std::to_string(b.version)+"."};if(a.fingerprint!=b.fingerprint)return {SchemaConfigCode::compatibility_mismatch,"Schema fingerprint mismatch."};return {};}
std::string SchemaConfig::generate_example_json(const ConfiguredSchema& s){std::ostringstream o;o<<"{\n";for(usize i=0;i<s.schema.fields.size();++i){const auto&f=s.schema.fields[i];o<<"  \""<<f.name<<"\": ";if(f.type==FieldType::string)o<<"\"example\"";else if(f.type==FieldType::bytes)o<<"\"0x00\"";else if(f.type==FieldType::f32||f.type==FieldType::f64)o<<"0.0";else o<<"0";o<<(i+1<s.schema.fields.size()?",\n":"\n");}return o<<"}\n",o.str();}
std::string SchemaConfig::generate_markdown(const ConfiguredSchema& s){std::ostringstream o;o<<"# "<<s.schema.schema_name<<"\n\nID: `"<<s.schema.message_id<<"`  Version: `"<<s.version<<"`  Fingerprint: `"<<std::hex<<s.fingerprint<<"`\n\n| Field | Type | Field ID | Constraints |\n|---|---|---:|---|\n";for(usize i=0;i<s.schema.fields.size();++i){const auto&f=s.schema.fields[i];o<<"| "<<f.name<<" | "<<field_type_to_string(f.type)<<" | "<<s.field_ids[i]<<" | "<<(f.constraints.has_max_length?"max length "+std::to_string(f.constraints.max_length):"-")<<" |\n";}return o.str();}
SchemaConfigResult register_configured_schema(SchemaRuntime& r,const ConfiguredSchema&s){auto x=r.register_schema(s.schema);return x.ok()?SchemaConfigResult{}:SchemaConfigResult{SchemaConfigCode::schema_invalid,x.message};}
// JSON text support is implemented with a deliberately strict flat-object grammar.
SchemaConfigResult parse_json_object(const std::string& text,JsonObject& out) {
 out.clear(); usize p=0; auto ws=[&](){while(p<text.size()&&std::isspace(static_cast<unsigned char>(text[p])))++p;}; auto str=[&](std::string& v){ws();if(p>=text.size()||text[p++]!='"')return false;v.clear();while(p<text.size()&&text[p]!='"'){if(text[p]=='\\'&&++p>=text.size())return false;v+=text[p++];}if(p>=text.size())return false;++p;return true;}; ws();if(p>=text.size()||text[p++]!='{')return {SchemaConfigCode::json_invalid,"JSON must be an object."};ws();if(p<text.size()&&text[p]=='}'){++p;return {};}
 while(true){std::string k,v;if(!str(k))return {SchemaConfigCode::json_invalid,"Expected quoted field name."};ws();if(p>=text.size()||text[p++]!=':')return {SchemaConfigCode::json_invalid,"Expected ':' after field '"+k+"'."};ws();JsonValue value;if(p<text.size()&&text[p]=='"'){if(!str(v))return {SchemaConfigCode::json_invalid,"Unterminated string for field '"+k+"'."};if(v.rfind("0x",0)==0){std::vector<byte>b;if((v.size()-2)%2)return {SchemaConfigCode::json_invalid,"Hex bytes require pairs for field '"+k+"'."};for(usize i=2;i<v.size();i+=2){u64 n;if(!number("0x"+v.substr(i,2),n))return {SchemaConfigCode::json_invalid,"Invalid hex bytes for field '"+k+"'."};b.push_back(static_cast<byte>(n));}value=JsonValue::from_bytes(b);}else value=JsonValue::from_string(v);}else{const usize s=p;while(p<text.size()&&text[p]!=','&&text[p]!='}'&&!std::isspace(static_cast<unsigned char>(text[p])))++p;v=text.substr(s,p-s);try{if(v.find_first_of(".eE")!=std::string::npos)value=JsonValue::from_decimal(std::stod(v));else value=JsonValue::from_integer(std::stoll(v));}catch(...){return {SchemaConfigCode::json_invalid,"Invalid number for field '"+k+"'."};}}out[k]=value;ws();if(p<text.size()&&text[p]==','){++p;continue;}if(p<text.size()&&text[p]=='}'){++p;ws();return p==text.size()?SchemaConfigResult{}:SchemaConfigResult{SchemaConfigCode::json_invalid,"Trailing JSON content."};}return {SchemaConfigCode::json_invalid,"Expected ',' or '}' after field '"+k+"'."}; }
}
std::string format_json_object(const JsonObject& object) { std::ostringstream o;o<<"{";usize i=0;for(const auto&x:object){if(i++)o<<",";o<<"\""<<json_escape(x.first)<<"\":";const auto&v=x.second;if(v.type==JsonValueType::string)o<<"\""<<json_escape(v.string_value)<<"\"";else if(v.type==JsonValueType::bytes){o<<"\"0x"<<std::hex<<std::setfill('0');for(byte b:v.bytes_value)o<<std::setw(2)<<static_cast<unsigned>(b);o<<std::dec<<"\"";}else if(v.type==JsonValueType::decimal)o<<v.decimal_value;else o<<v.integer_value;}return o<<"}",o.str(); }
} // namespace keydrop
